### PR TITLE
Specify https index to fix buildout, update changelog

### PR DESCRIPTION
**Pull request by davisagli**
Here is a fix for the "Couldn't find a distribution" errors that doesn't require messing with buildout and setuptools versions.

### CODE REVIEW

**Comment by caseylitton** [comment]
Per the other PR(#56) let's add version .31 to the CHANGES.rst for this pr.

**Comment by davisagli** [comment]
It's a little frustrating to be asked to write a changelog entry for a one-line development-only fix after multiple releases of the changelog not being updated at all, but I agree with the goal of having a useful changelog and am spending some time trying to fill in the missing entries.

**Comment by davisagli** [comment]
@caseylitton this PR now includes backfilling the changelog.

**Comment by davisagli** [comment]
Anyone recognize the way the build is failing?

**Comment by davisagli** [comment]
Looks like it's failing to connect to the webdriver remote. Did something change about that?

**Comment by caseylitton** [comment]
Not sure, I restarted them.  You other prs have passing.

**Pull request merged**
