### PR TITLE
added error message for invalid login

### PR DESCRIPTION
**Pull request by j1z0**

### CODE REVIEW

**Comment by hitz** [comment]
I see the error message but only in the JS console.
Also, I am not sure what the "demo" username / password is; probably I could figure it out from the code.
I thought it was admin@admin.com / admin  but that doesn't work on my local install.

**Comment by j1z0** [comment]
@hitz -- ahh sorry minor typo in the js.  It's fixed now.  Also for the demo user I've changed the `load_test_data` function (snowflakes/loadxl.py:523) to create accounts for all users in test/data/inserts with password `Steve`.

**Comment by hitz** [comment]
Sorry I am behind on this.  I want to fix the cloud-config first.

**Comment by hitz** [comment]
Merged in #15

**Pull request closed without merging**
